# This is a workflow to compile the cdeps source without cime
name: extbuild
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main, "feature/**" ]
  pull_request:
    branches: [ main, "feature/**" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-cdeps:
    runs-on: ubuntu-latest
    container:
      image: noaaepic/ubuntu22.04-intel2024.2.0-1-devel-wm:ue192-hsd-aquaplanet
    env:
      ESMF_VERSION: v8.6.1
      ParallelIO_VERSION: pio2_6_2
    steps:
      - id: checkout-CDEPS
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache Docker image
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-noaaepic-ubuntu22.04-intel2024.2.0-1-devel-wm-ue192-hsd-aquaplanet

      - name: Explore Environment
        shell: bash
        run: |
          echo "Checking PATH..."
          echo $PATH
          echo "Checking for Intel environment..."
          [ -f /opt/intel/oneapi/setvars.sh ] && source /opt/intel/oneapi/setvars.sh || echo "setvars.sh not found"
          echo "Checking Environment Variables..."
          env | sort
          echo "Checking for MPI..."
          which mpirun || echo "mpirun not found"
          which mpicc || echo "mpicc not found"
          which mpifort || echo "mpifort not found"
          echo "Checking for Intel compilers..."
          which icc || echo "icc not found"
          which ifort || echo "ifort not found"
          which icx || echo "icx not found"
          which ifx || echo "ifx not found"
          echo "Checking for libraries..."
          find /usr/local -name "libpio*" || echo "PIO lib not found in /usr/local"
          find /usr/lib -name "libpio*" || echo "PIO lib not found in /usr/lib"
          find /opt -name "libpio*" || echo "PIO lib not found in /opt"
          find /usr/local -name "esmf.mk" || echo "esmf.mk not found in /usr/local"

      - name: Build CDEPS
        shell: bash
        run: |
          [ -f /opt/intel/oneapi/setvars.sh ] && source /opt/intel/oneapi/setvars.sh
          mkdir build-cdeps
          cd build-cdeps
          export ESMFMKFILE=/usr/local/lib/esmf.mk
          export PIO=/usr/local
          cmake -Wno-dev -DCMAKE_BUILD_TYPE=DEBUG -DWERROR=ON -DCMAKE_Fortran_FLAGS="-g -O2" ${GITHUB_WORKSPACE}
          make -j$(nproc) VERBOSE=1

      - name: Test CDEPS
        run: |
          cd build-cdeps
          make VERBOSE=1
