# This is a workflow to compile the cdeps source without cime
name: extbuild
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main, "feature/**" ]
  pull_request:
    branches: [ main, "feature/**" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-cdeps:
    runs-on: ubuntu-latest
    container:
      image: jcsda/docker-gnu-openmpi-dev:1.9
    steps:
      - id: checkout-CDEPS
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build CDEPS
        shell: bash
        run: |
          source /opt/spack-environment/activate.sh
          mkdir build
          cd build
          # Use PIO and ESMF from the JCSDA environment
          export PIO_PATH=$(find /opt/software -name "libpioc.so" | head -n 1 | xargs dirname | xargs dirname)
          cmake -Wno-dev -DCMAKE_BUILD_TYPE=DEBUG -DWERROR=ON -DDISABLE_FoX=ON -DPIO_PATH=${PIO_PATH} ${GITHUB_WORKSPACE}
          make -j$(nproc) VERBOSE=1

      - name: Test CDEPS
        run: |
          cd build
          make VERBOSE=1
