# This is a workflow to compile the cdeps source without cime
name: extbuild
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main, "feature/**" ]
  pull_request:
    branches: [ main, "feature/**" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-cdeps:
    runs-on: ubuntu-latest
    container:
      image: noaaepic/ubuntu22.04-intel2024.2.0-1-devel-wm:ue192-hsd-aquaplanet
    env:
      CC: mpicc
      FC: mpifort
      CXX: mpicxx
      # Versions of all dependencies can be updated here - these match tag names in the github repo
      ESMF_VERSION: v8.6.1
      ParallelIO_VERSION: pio2_6_2
    steps:
      - id: checkout-CDEPS
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache PARALLELIO
        id: cache-PARALLELIO
        uses: actions/cache@v4
        with:
          path: ${GITHUB_WORKSPACE}/pio
          key: ${{ runner.os }}-${{ env.ParallelIO_VERSION }}-parallelio2

      - name: Build ParallelIO
        if: steps.cache-PARALLELIO.outputs.cache-hit != 'true'
        uses: NCAR/ParallelIO/.github/actions/parallelio_cmake@9390e30e29d4ebbfbef0fc72162cacd9e8f25e4e
        with:
          parallelio_version: ${{ env.ParallelIO_VERSION }}
          enable_fortran: True
          install_prefix: ${GITHUB_WORKSPACE}/pio

      - name: Build CDEPS
        uses: ./.github/actions/buildcdeps
        with:
          esmfmkfile: /usr/local/lib/esmf.mk
          pio_path: ${GITHUB_WORKSPACE}/pio
          src_root: ${GITHUB_WORKSPACE}
          cmake_flags: " -Wno-dev -DCMAKE_BUILD_TYPE=DEBUG -DWERROR=ON  -DCMAKE_Fortran_FLAGS=\"-g -O2 \""

      - name: Test CDEPS
        run: |
          cd build-cdeps
          make VERBOSE=1
